name: SolScout Alert Bot

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main          # Ensure the branch matches where your updates were committed
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the entire history to ensure it grabs the latest code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python bot.py
